### PR TITLE
Update to handle name change from 3PC -> PArSEC

### PR DESCRIPTION
**Pull request by maurermi**
This PR updates the codebase to handle the name change of 3PC to PArSEC. There are two commits in this PR currently, the first updates occurrences of 3PC to parsec, and the second updates occurrences of "phase two"

### CODE REVIEW

**Comment by HalosGhost** [comment]
Conditional T-ACK. Just to double-check: there are no default component configurations selected for parsec, and only four component roles are present (agent, shard, ticket machine, generator). Is this expected?

**Comment by maurermi** [comment]
@HalosGhost from what I can tell, that is how the test controller currently operates for 3pc, though it may make sense to add default values. Also, the four components you listed should be all that is required (system core is an agent, ticket machine, and shard, and the load generator acts like a set of users)

**Comment by HalosGhost** [comment]
~I think adding a default configuration is an incredibly good idea so that it's easy for people to dip their toes in.~

Scratching the above (opened #16 as a future item) so this isn't blocked. Given that I've already t-ACK'd; if my in-progress testing of #12 is successful, it will be merged and should automatically close this.

**Review by HalosGhost — APPROVED** [review]
As there's an open question on #12; merging!

**Pull request merged**
